tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - sainnhe.gruvbox-material
    - gulajavaministudio.mayukaithemevsc
